spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jira_platform
    username: jiraadmin
    password: ${DB_PASSWORD:localpass}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

management:
  endpoint:
    health:
      show-details: always