server:
  port: 8094

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:jira_platform}
    username: ${DB_USERNAME:jiraadmin}
    password: ${DB_PASSWORD:jirapass123}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: jira_migration
  flyway:
    enabled: true
    schemas: jira_migration
    default-schema: jira_migration
    create-schemas: true
    baseline-on-migrate: true
    validate-on-migrate: false

services:
  gatewayServiceUrl: http://gateway:8080
  authServiceUrl: http://auth-service:8081
  userServiceUrl: http://user-service:8082
  projectServiceUrl: http://project-service:8083
  issueServiceUrl: http://issue-service:8084
  workflowServiceUrl: http://workflow-service:8085
  commentServiceUrl: http://comment-service:8086
  notificationServiceUrl: http://notification-service:8087
  searchServiceUrl: http://search-service:8088
  auditServiceUrl: http://audit-service:8089
  attachmentServiceUrl: http://attachment-service:8090
  sprintServiceUrl: http://sprint-service:8091
  planServiceUrl: http://plan-service:8092
  adminServiceUrl: http://admin-service:8093
  migrationServiceUrl: http://migration-service:8094
  testServiceUrl: http://test-service:8095

jira:
  services:
    workflow-url: http://workflow-service:8085
    issue-url: http://issue-service:8084

cluster:
  enabled: false
