spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avionics_systems_platform
    username: avionicsadmin
    password: ${DB_PASSWORD:localpass}
  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:db/init-local.sql
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics