spring:
  config:
    activate:
      on-profile: external
  datasource:
    url: jdbc:postgresql://in0-eplmdb-v01:5432/systems
    username: systems_admin
    password: Hcu4ieD8R13qaf7JVSsu
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: jira_search
  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: jira_search
    schemas: jira_search
    create-schemas: true
    validate-on-migrate: false
    locations: filesystem:migrations-external/jira-search-service

logging:
  level:
    com.jira.search: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
