spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jira_platform
    username: jiraadmin
    password: UNIpay@123
  flyway:
    validate-on-migrate: false

jira:
  permissions:
    fail-open: true

jira.services.issue-url: http://localhost:8084
jira.services.project-url: http://localhost:8083