spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
  jpa:
    properties:
      hibernate:
        default_schema: jira_auth
  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: jira_auth
    schemas: jira_auth
    create-schemas: true
