spring:
  config:
    activate:
      on-profile: external
  datasource:
    url: jdbc:postgresql://in0-eplmdb-v01:5432/systems
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: jira_admin
  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: jira_admin
    schemas: jira_admin
    create-schemas: true
    validate-on-migrate: false
    locations: filesystem:migrations-external/jira-admin-service

logging:
  level:
    com.jira.admin: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
