spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/jira_platform
    username: jiraadmin
    password: ${DB_PASSWORD:localpass}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false