FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /build

COPY .m2-cache /root/.m2/repository

COPY jira-user-service/pom.xml .
COPY jira-user-service/src ./src

RUN mvn package -Dmaven.test.skip=true -o -q

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
RUN addgroup -S appuser && adduser -S appuser -G appuser
COPY --from=builder /build/target/*.jar app.jar
RUN chown -R appuser:appuser /app
USER appuser
EXPOSE 8082
ENTRYPOINT ["java","-jar","app.jar"]
