spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avionics_systems_platform
    username: avionicsadmin
    password: ${DB_PASSWORD:UNIpay@123}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    schemas: jira_project
    default-schema: jira_project
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8083

issue:
  service:
    url: http://localhost:8084

logging:
  level:
    com.avionics_systems.project: INFO
    org.springframework.web: WARN