spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avionics_systems_platform
    username: avionicsadmin
    password: ${DB_PASSWORD:localpass}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

management:
  endpoint:
    health:
      show-details: always