avionics-systems:
  issue-service-url: http://localhost:8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avionics_systems_platform
    username: avionicsadmin
    password: ${DB_PASSWORD:localpass}
  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:db/init-local.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: jira_sprint

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics