apiVersion: v1
kind: Namespace
metadata:
  name: avionics-systems-platform
  labels:
    name: avionics-systems-platform
    environment: production
    app.kubernetes.io/name: avionics-systems-platform
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: avionics-systems-platform-ingress
  labels:
    name: avionics-systems-platform-ingress