spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_db
    username: jiraadmin
    password: UNIpay@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8083

logging:
  level:
    com.jira.project: INFO
    org.springframework.web: WARN